/*
 * Progetto Università Parthenope di Programmazione 3
 * Mario Daniele 0124001808.
 */
package it.uniparthenope.prog3.daniele.mario.marketmanager.view;

import it.uniparthenope.prog3.daniele.mario.marketmanager.controller.CategoryController;
import it.uniparthenope.prog3.daniele.mario.marketmanager.exception.StringEmptyException;
import it.uniparthenope.prog3.daniele.mario.marketmanager.model.builder.category.Category;

import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 * Permette all'utente di interagire con le entità {@code Category} con un
 * approccio CRUD.
 * 
 * @see Category
 *
 * @author Mario Daniele 0124001808
 * @since 1.0
 * @version 1.0
 */
public class CategoryView extends javax.swing.JFrame {

    /**
     * Inizializza i componenti grafici e la tabella delle categorie.
     * 
     * @throws java.sql.SQLException
     * @see #initComponents()
     * @see #populateTable()
     */
    public CategoryView() throws SQLException {
        
        this.initComponents();
        this.populateTable();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        catName = new javax.swing.JTextField();
        addButton = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        catDesc = new javax.swing.JTextField();
        deleteButton = new javax.swing.JButton();
        editButton = new javax.swing.JButton();
        clearButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        categoryTable = new javax.swing.JTable();
        jLabel12 = new javax.swing.JLabel();
        productButtonLabel = new javax.swing.JLabel();
        logoutButtonLabel = new javax.swing.JLabel();
        sellerButtonLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel3.setBackground(new java.awt.Color(255, 204, 0));

        jPanel4.setBackground(new java.awt.Color(204, 204, 204));

        catName.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N

        addButton.setBackground(new java.awt.Color(255, 204, 0));
        addButton.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        addButton.setText("AGGIUNGI");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Century Gothic", 1, 36)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("MANAGER CATEGORIE");

        jLabel9.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel9.setText("DESCRIZIONE");

        jLabel10.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel10.setText("NOME");

        catDesc.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N

        deleteButton.setBackground(new java.awt.Color(255, 204, 0));
        deleteButton.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        deleteButton.setText("CANCELLA");
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });

        editButton.setBackground(new java.awt.Color(255, 204, 0));
        editButton.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        editButton.setText("MODIFICA");
        editButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editButtonActionPerformed(evt);
            }
        });

        clearButton.setBackground(new java.awt.Color(255, 204, 0));
        clearButton.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        clearButton.setText("PULISCI");
        clearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearButtonActionPerformed(evt);
            }
        });

        categoryTable.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        categoryTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "NOME", "DESCRIZIONE"
            }
        ));
        categoryTable.setRowHeight(24);
        categoryTable.setSelectionBackground(new java.awt.Color(255, 204, 0));
        categoryTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                categoryTableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(categoryTable);

        jLabel12.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("LISTA CATEGORIE");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(18, 18, 18)
                        .addComponent(catName, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(catDesc, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2)
                    .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(61, Short.MAX_VALUE)
                .addComponent(addButton, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(editButton, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(deleteButton)
                .addGap(18, 18, 18)
                .addComponent(clearButton, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(catName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(catDesc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addButton)
                    .addComponent(editButton)
                    .addComponent(clearButton)
                    .addComponent(deleteButton))
                .addGap(18, 18, 18)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 452, Short.MAX_VALUE)
                .addContainerGap())
        );

        productButtonLabel.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        productButtonLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        productButtonLabel.setText("PRODOTTI");
        productButtonLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                productButtonLabelMouseClicked(evt);
            }
        });

        logoutButtonLabel.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        logoutButtonLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logoutButtonLabel.setText("LOGOUT");
        logoutButtonLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutButtonLabelMouseClicked(evt);
            }
        });

        sellerButtonLabel.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        sellerButtonLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        sellerButtonLabel.setText("VENDITORI");
        sellerButtonLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sellerButtonLabelMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(logoutButtonLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(sellerButtonLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(productButtonLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(productButtonLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(sellerButtonLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(logoutButtonLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void logoutButtonLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutButtonLabelMouseClicked
        
        this.categoryController.logoutPressed();
        
    }//GEN-LAST:event_logoutButtonLabelMouseClicked

    private void productButtonLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_productButtonLabelMouseClicked
     
        try {
            
            this.categoryController.switchToProductView();
            
        } catch (SQLException ex) {
            
            Logger.getLogger(CategoryView.class.getName()).log(Level.SEVERE, null, ex);
            
        }
        
    }//GEN-LAST:event_productButtonLabelMouseClicked

    private void sellerButtonLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sellerButtonLabelMouseClicked
        
        try {
            
            this.categoryController.switchToSellerView();
            
        } catch (SQLException ex) {
            
            Logger.getLogger(CategoryView.class.getName()).log(Level.SEVERE, null, ex);
            
        }
        
    }//GEN-LAST:event_sellerButtonLabelMouseClicked

    private void clearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearButtonActionPerformed
       
        this.clearTextFieldCategory();
        
    }//GEN-LAST:event_clearButtonActionPerformed

    private void categoryTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_categoryTableMouseClicked
        
        this.categoryTable.setDefaultEditor(Object.class, null);
        
        int rowIndexPK = categoryTable.getSelectedRow();
        
        Category category = categoryList.get(rowIndexPK);

        this.catName.setText(category.getName());
        this.catDesc.setText(category.getDescription());
        
        this.clickName = catName.getText();
        
    }//GEN-LAST:event_categoryTableMouseClicked

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        
        try {
            
            this.categoryController.addPressed(catName.getText(), catDesc.getText());
            
            this.categoryList = categoryController.initTable();
            
            this.populateTable();
            
        } catch (SQLException ex) {
            
            JOptionPane.showMessageDialog(this, "ERRORE: categoria già esistente");
            
            Logger.getLogger(CategoryView.class.getName()).log(Level.SEVERE, null, ex);
            
        } catch (StringEmptyException ex) {
            
            JOptionPane.showMessageDialog(this, ex.getMessage());
            
            Logger.getLogger(CategoryView.class.getName()).log(Level.SEVERE, null, ex);
            
        }
        
    }//GEN-LAST:event_addButtonActionPerformed

    private void editButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editButtonActionPerformed
        
        try {
            
            this.categoryController.updatePressed(catName.getText(), catDesc.getText(), clickName);
            
            this.categoryList = categoryController.initTable();
            
            this.populateTable();
            
        } catch (SQLException ex) {
            
            JOptionPane.showMessageDialog(this, "ERRORE: categoria già esistente");
            
            Logger.getLogger(CategoryView.class.getName()).log(Level.SEVERE, null, ex);
            
        } catch (StringEmptyException ex) {
            
            JOptionPane.showMessageDialog(this, ex.getMessage());
            
            Logger.getLogger(CategoryView.class.getName()).log(Level.SEVERE, null, ex);
            
        }
        
    }//GEN-LAST:event_editButtonActionPerformed

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed

        try {
            
            this.categoryController.deletePressed(catName.getText());
            
            this.categoryList = categoryController.initTable();
            
            this.populateTable();
            
        } catch (SQLException ex) {
            
            Logger.getLogger(CategoryView.class.getName()).log(Level.SEVERE, null, ex);
            
        }
        
    }//GEN-LAST:event_deleteButtonActionPerformed

    /**
     * Azzera i campi di testo dell'interfaccia relativi alla categoria.
     */
    private void clearTextFieldCategory() {
        
        this.catName.setText("");
        this.catDesc.setText("");
        
    }
    
    /** Popola la tabella della finestra */
    public void populateTable() throws SQLException {
        
        DefaultTableModel tblModel = (DefaultTableModel)categoryTable.getModel();
                 
        tblModel.setRowCount(0);
        
        this.categoryTable.setDefaultEditor(Object.class, null);
        
        Integer columns = 2;
        
        Object[] row = new Object[columns];
        
        for(int indice = 0; indice < categoryList.size(); indice++){
            
            row[0] = categoryList.get(indice).getName();
            row[1] = categoryList.get(indice).getDescription();
            
            tblModel.addRow(row);
            
        }
        
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CategoryView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CategoryView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CategoryView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CategoryView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new CategoryView().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(SellingView.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }
    
    /** Inizializza la variabile per il nome della categoria selezionato */
    private String clickName = null;
    
    /** L'istanza del controller associato a questa view */
    private final CategoryController categoryController = new CategoryController(this);
    
    /** Crea una lista di categorie restituita dal controller */
    private ArrayList<Category> categoryList = categoryController.initTable();

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JTextField catDesc;
    private javax.swing.JTextField catName;
    private javax.swing.JTable categoryTable;
    private javax.swing.JButton clearButton;
    private javax.swing.JButton deleteButton;
    private javax.swing.JButton editButton;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel logoutButtonLabel;
    private javax.swing.JLabel productButtonLabel;
    private javax.swing.JLabel sellerButtonLabel;
    // End of variables declaration//GEN-END:variables
}
