/*
 * Progetto Università Parthenope di Programmazione 3
 * Mario Daniele 0124001808.
 */
package it.uniparthenope.prog3.daniele.mario.marketmanager.view;

import it.uniparthenope.prog3.daniele.mario.marketmanager.controller.SellerController;
import it.uniparthenope.prog3.daniele.mario.marketmanager.exception.StringEmptyException;
import it.uniparthenope.prog3.daniele.mario.marketmanager.model.factory.Account;

import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 * Permette all'utente di interagire con le entità {@code Account} di tipo
 * {@code AccountType.SELLER} con un approccio CRUD.
 * 
 * @see Account
 * @see AccountType
 * @see AccountFactory
 * @see Admin
 * @see Seller
 *
 * @author Mario Daniele 0124001808
 * @since 1.0
 * @version 1.0
 */
public class SellerView extends javax.swing.JFrame {

    /**
     * Creates new form SellerView
     * @throws java.sql.SQLException
     */
    public SellerView() throws SQLException {
        
        this.initComponents();
        this.populateTable();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        addButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        selName = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        selPass = new javax.swing.JTextField();
        deleteButton = new javax.swing.JButton();
        editButton = new javax.swing.JButton();
        clearButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        sellerTable = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        categoryButtonLabel = new javax.swing.JLabel();
        logoutButtonLabel = new javax.swing.JLabel();
        productButtonLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 204, 0));

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));

        addButton.setBackground(new java.awt.Color(255, 204, 0));
        addButton.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        addButton.setText("AGGIUNGI");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("MANAGER VENDITORI");

        jLabel3.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel3.setText("PASSWORD");

        selName.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel4.setText("NOME");

        selPass.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N

        deleteButton.setBackground(new java.awt.Color(255, 204, 0));
        deleteButton.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        deleteButton.setText("CANCELLA");
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });

        editButton.setBackground(new java.awt.Color(255, 204, 0));
        editButton.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        editButton.setText("MODIFICA");
        editButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editButtonActionPerformed(evt);
            }
        });

        clearButton.setBackground(new java.awt.Color(255, 204, 0));
        clearButton.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        clearButton.setText("PULISCI");
        clearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearButtonActionPerformed(evt);
            }
        });

        sellerTable.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        sellerTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "USERNAME", "PASSWORD"
            }
        ));
        sellerTable.setRowHeight(24);
        sellerTable.setSelectionBackground(new java.awt.Color(255, 204, 0));
        sellerTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sellerTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(sellerTable);

        jLabel8.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("LISTA VENDITORI");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(selName, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(selPass, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(58, Short.MAX_VALUE)
                .addComponent(addButton, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(editButton, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(deleteButton)
                .addGap(18, 18, 18)
                .addComponent(clearButton, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(selPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(selName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(74, 74, 74)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addButton)
                    .addComponent(editButton)
                    .addComponent(clearButton)
                    .addComponent(deleteButton))
                .addGap(18, 18, 18)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 396, Short.MAX_VALUE)
                .addContainerGap())
        );

        categoryButtonLabel.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        categoryButtonLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        categoryButtonLabel.setText("CATEGORIE");
        categoryButtonLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                categoryButtonLabelMouseClicked(evt);
            }
        });

        logoutButtonLabel.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        logoutButtonLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logoutButtonLabel.setText("LOGOUT");
        logoutButtonLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutButtonLabelMouseClicked(evt);
            }
        });

        productButtonLabel.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        productButtonLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        productButtonLabel.setText("PRODOTTI");
        productButtonLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                productButtonLabelMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(logoutButtonLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(categoryButtonLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(productButtonLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(productButtonLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(categoryButtonLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(logoutButtonLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void logoutButtonLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutButtonLabelMouseClicked
        
        this.sellerController.logoutPressed();
        
    }//GEN-LAST:event_logoutButtonLabelMouseClicked

    private void productButtonLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_productButtonLabelMouseClicked
        
        try {
            
            this.sellerController.switchToProductView();
            
        } catch (SQLException ex) {
            
            Logger.getLogger(SellerView.class.getName()).log(Level.SEVERE, null, ex);
            
        } catch (StringEmptyException ex) {
            
            JOptionPane.showMessageDialog(null, ex.getMessage());
            
            Logger.getLogger(SellerView.class.getName()).log(Level.SEVERE, null, ex);
            
        }
        
    }//GEN-LAST:event_productButtonLabelMouseClicked

    private void categoryButtonLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_categoryButtonLabelMouseClicked
        
        try {
            
            this.sellerController.switchToCategoryView();
            
        } catch (SQLException ex) {
            
            Logger.getLogger(SellerView.class.getName()).log(Level.SEVERE, null, ex);
            
        } catch (StringEmptyException ex) {
            
            JOptionPane.showMessageDialog(this, ex.getMessage());
            
            Logger.getLogger(SellerView.class.getName()).log(Level.SEVERE, null, ex);
            
        }
        
    }//GEN-LAST:event_categoryButtonLabelMouseClicked

    private void clearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearButtonActionPerformed
        
        this.clearTextFieldSeller();
        
    }//GEN-LAST:event_clearButtonActionPerformed

    private void sellerTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sellerTableMouseClicked
        
        this.sellerTable.setDefaultEditor(Object.class, null);
        
        int rowIndexPK = sellerTable.getSelectedRow();
        
        Account seller = sellerList.get(rowIndexPK);

        this.selName.setText(seller.getUsername());
        this.selPass.setText(seller.getPassword());
        
        this.clickUsername = selName.getText();
        
    }//GEN-LAST:event_sellerTableMouseClicked

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        
        try {
            
            this.sellerController.addPressed(selName.getText(), selPass.getText());
            
            this.sellerList = sellerController.initTable();
            
            this.populateTable();
            
        } catch (SQLException ex) {
            
            JOptionPane.showMessageDialog(this, "ERRORE: Account già esistente");
            
            Logger.getLogger(SellerView.class.getName()).log(Level.SEVERE, null, ex);
            
        } catch (StringEmptyException ex) {
            
            JOptionPane.showMessageDialog(this, ex.getMessage());
            
            Logger.getLogger(SellerView.class.getName()).log(Level.SEVERE, null, ex);
            
        }
        
    }//GEN-LAST:event_addButtonActionPerformed

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed

            
        try {
            
            this.sellerController.deletePressed(selName.getText());
            
            this.sellerList = sellerController.initTable();
            
            this.populateTable();
            
        } catch (SQLException ex) {
            
            Logger.getLogger(SellerView.class.getName()).log(Level.SEVERE, null, ex);
            
        }
        
    }//GEN-LAST:event_deleteButtonActionPerformed

    private void editButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editButtonActionPerformed
        
        try {
            
            this.sellerController.updatePressed(selName.getText(), selPass.getText(), clickUsername);
            
            this.sellerList = sellerController.initTable();
            
            this.populateTable();
            
        } catch (SQLException ex) {
            
            JOptionPane.showMessageDialog(this, "ERRORE: Account già esistente");
            
            Logger.getLogger(SellerView.class.getName()).log(Level.SEVERE, null, ex);
            
        } catch (StringEmptyException ex) {
            
            JOptionPane.showMessageDialog(this, ex.getMessage());
            
            Logger.getLogger(SellerView.class.getName()).log(Level.SEVERE, null, ex);
            
        }
        
    }//GEN-LAST:event_editButtonActionPerformed

    /** Popola la tabella della finestra */
    public void populateTable() {
        
        DefaultTableModel tblModel = (DefaultTableModel)sellerTable.getModel();
                 
        tblModel.setRowCount(0);
        
        this.sellerTable.setDefaultEditor(Object.class, null);
        
        Integer columns = 2;
        
        Object[] row = new Object[columns];
        
        for(int indice = 0; indice < sellerList.size(); indice++){
            
            row[0] = sellerList.get(indice).getUsername();
            row[1] = sellerList.get(indice).getPassword();
            
            tblModel.addRow(row);
            
        }
        
    }
    
    /**
     * Azzera i campi di testo dell'interfaccia relativi ai venditori.
     */
    private void clearTextFieldSeller() {
        
        this.selName.setText("");
        this.selPass.setText("");
        
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SellerView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SellerView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SellerView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SellerView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    
                    new SellerView().setVisible(true);
                    
                } catch (SQLException ex) {
                    
                    Logger.getLogger(SellerView.class.getName()).log(Level.SEVERE, null, ex);
                    
                }
            }
        });
    }
    
    /** L'istanza del controller associato a questa view */
    private final SellerController sellerController = new SellerController(this);

    /** Crea una lista di account restituita dal controller */
    private ArrayList<Account> sellerList = sellerController.initTable();
    
    /** Inizializza la variabile per il nome utente del'account selezionato */
    private String clickUsername = null;
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JLabel categoryButtonLabel;
    private javax.swing.JButton clearButton;
    private javax.swing.JButton deleteButton;
    private javax.swing.JButton editButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel logoutButtonLabel;
    private javax.swing.JLabel productButtonLabel;
    private javax.swing.JTextField selName;
    private javax.swing.JTextField selPass;
    private javax.swing.JTable sellerTable;
    // End of variables declaration//GEN-END:variables
}
